### ISSUE TITLE
[Question]: base_path

### ISSUE THREAD

**Issue by windowsrefund** [Weyaaron/nvim-training#32]
### Question

I was going to throw together a PR but I'm not really a lua guy and honestly, the code confuses me. Better to just raise the question/concern and let the Jedi here figure it out:

Basically, I don't want my `~` used as a dumping ground for a given neovim plugin. I know I can override `base_path` but honestly, I think the plugin should be following normal conventions and just use `vim.fn.stdpath("data") .. "nvim-training")` as a default. That way, you can just write the directory and forego the need to prompt the user with the question, etc, etc...

An example of a plugin using this approach can be seen [here](https://github.com/search?q=repo%3Aarjunmahishi%2Fflow.nvim%20stdpath&type=code)

Also, I did notice there are these .flac files. Can we not do that please? :)

**Comment by Weyaaron** [comment]
Hi @windowsrefund , 

sorry for being somewhat late, I will work on these points. I agree that the base_path should be changed, I will do this soon.

What about the flac files is not to your liking? As far as I can tell, flac is a open source format. I am open to providing better/other formats.

**Comment by Weyaaron** [comment]
#33  has adressed the point about the base_path. I will keep this issue open to discuss the flac files.

**Comment by windowsrefund** [comment]
Thanks for the work on `base_path`. As for the audio files, it has nothing to do with the format. Editors shouldn't make noise.

**Comment by Weyaaron** [comment]
I would agree for the most part, but I disagree in this particular case. I appreciate the immediate feedback of the sound. For sure, the overall feedback of the ui should be improved, but I consider the audio essential for quick feedback. And since this is configurable, it can be turned off in a user-friendly manner. And I would like to keep it on in the default configuration because I think there are immediate benefits to it.

**Comment by windowsrefund** [comment]
With all due respect, why would you need audio feedback when you're looking at the editor? It's not as if we're talking about a background task of sorts which can be expected to run async and forgotten about. Your eyes are staring right at the the very thing that is expected to provide visual feedback. Are you sure you're not just emotionally conditioned to think you benefit from (redundant) audio feedback? I've seen this trend with folks running OSX where they're constantly bombarded with blings and beeps produced by the notification widget. What's especially funny is how these same people tend to just tune it out and over time, don't even notice the sounds coming from their systems. They join meetings where the rest of us have to endure these odd noises which are clearly being ignored by the person they're supposed to be serving.

So we most definitely do not agree on the value of these but if they must exist, they should 100% be disabled by default.

**Comment by Weyaaron** [comment]
This question has been migrated to the proper issue, and since the changes to the base_path have been made, this issue can be closed.
