### ISSUE TITLE
[Question]: getting errors when I start the training 

### ISSUE THREAD

**Issue by SAbruzzo** [Weyaaron/nvim-training#48]
### Question

Hi, I am getting an error when I start the plugin and seems to not work 
<img width="1727" alt="image" src="https://github.com/user-attachments/assets/eed0565f-5dbe-4e2d-937d-d4b30df04486" />

This is my configuration https://github.com/SAbruzzo/nvim-config/blob/nvim-lazy/lua/plugins/nvim-training.lua
and this is my version of nvim 

`➜  nvim --version
NVIM v0.10.3
Build type: Release
LuaJIT 2.1.1734355927`

If I run again I get a different error 
`Error detected while processing CursorMoved Autocommands for "*":
Error executing lua callback: ...re/nvim/lazy/nvim-training/lua/nvim-training/utility.lua:360: attempt to index local 'file' (a nil value)
stack traceback:
	...re/nvim/lazy/nvim-training/lua/nvim-training/utility.lua:360: in function 'append_json_to_file'
	...re/nvim/lazy/nvim-training/lua/nvim-training/logging.lua:19: in function 'log_to_file'
	...re/nvim/lazy/nvim-training/lua/nvim-training/logging.lua:28: in function 'log'
	...nvim/lazy/nvim-training/lua/nvim-training/tasks/move.lua:21: in function 'deactivate'`
Could it be that something was not created properly during the install of the plugin?

**Comment by Weyaaron** [comment]
Hi, thanks for the detailed report. A fix will probably happen today, I will keep you informed on progresss :)

**Comment by Weyaaron** [comment]
Your issue contained two problems, both have been addressed. Please make sure to force Lazy to update to get the new code.

Thanks for reporting it, If you have any follow-up issues let me know, I will help out.

**Comment by SAbruzzo** [comment]
thank you - I confirm it works now.
